# -*- coding: utf-8 -*-
"""Preprocessor_EXP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mm17MxRWD_JoRHTJmHyHtkG3Hbn_mwa4

# Experiment: Batch Preprocessor (Denoise -> Deblur -> CLAHE)

This notebook processes **all images in a given input directory** using the pipeline:

1. **Denoise** (SwinIR grayscale denoising)
2. **Deblur** (NAFNet)
3. **CLAHE** (contrast enhancement)

Outputs are saved into a new directory, then zipped and made ready to download.
"""

from __future__ import annotations

from google.colab import drive
drive.mount('/content/drive')

"""## What This Notebook Produces

- A processed output directory containing one final image per input image.
- A zip archive of that output directory.
- A random visualization of up to 5 images with 4 columns:
  - Original image
  - After Denoise
  - After Denoise + Deblur
  - After Denoise + Deblur + CLAHE (Final)

"""


import os
import sys
import cv2
import json
import time
import shutil
import random
import zipfile
import subprocess
import importlib.util
from pathlib import Path
from shlex import quote as shell_quote

import numpy as np
import matplotlib.pyplot as plt
import torch

WORK_DIR = Path('.').resolve()
NAFNET_DIR = WORK_DIR / 'NAFNet'
SWINIR_DIR = WORK_DIR / 'SwinIR'
NAFNET_WEIGHT_DIR = NAFNET_DIR / 'experiments' / 'pretrained_models'
SWINIR_MODEL_DIR = SWINIR_DIR / 'experiments' / 'pretrained_models'

print('WORK_DIR:', WORK_DIR)
print('NAFNET_DIR:', NAFNET_DIR)
print('SWINIR_DIR:', SWINIR_DIR)

def run(cmd: str, cwd: Path | None = None) -> None:
    print(f"$ {cmd}")
    subprocess.run(cmd, shell=True, check=True, cwd=None if cwd is None else str(cwd))

# 1) Clone repositories and install dependencies

if not NAFNET_DIR.exists():
    run('git clone https://github.com/megvii-research/NAFNet')
else:
    print('NAFNet repo already exists, skipping clone.')

if not SWINIR_DIR.exists():
    run('git clone https://github.com/JingyunLiang/SwinIR.git')
else:
    print('SwinIR repo already exists, skipping clone.')

run('pip install -r requirements.txt', cwd=NAFNET_DIR)
run('pip install --upgrade --no-cache-dir gdown', cwd=NAFNET_DIR)
run('python3 setup.py develop --no_cuda_ext', cwd=NAFNET_DIR)
run('pip install timm')

# 2) Download pretrained models

import gdown

NAFNET_WEIGHT_DIR.mkdir(parents=True, exist_ok=True)
SWINIR_MODEL_DIR.mkdir(parents=True, exist_ok=True)

# NAFNet weight link from NAFNet demo notebook
nafnet_url = 'https://drive.google.com/uc?id=14D4V4raNYIOhETfcuuLI3bGLB-OYIv6X'
nafnet_weight = NAFNET_WEIGHT_DIR / 'NAFNet-REDS-width64.pth'
if not nafnet_weight.exists():
    gdown.download(nafnet_url, str(NAFNET_WEIGHT_DIR) + '/', quiet=False)
else:
    print('NAFNet weight already exists:', nafnet_weight)

# SwinIR grayscale denoising model links (same release style as SwinIR notebook)
swinir_gray_dn_urls = {
    15: 'https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/004_grayDN_DFWB_s128w8_SwinIR-M_noise15.pth',
    25: 'https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/004_grayDN_DFWB_s128w8_SwinIR-M_noise25.pth',
    50: 'https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/004_grayDN_DFWB_s128w8_SwinIR-M_noise50.pth',
}

for noise_level, url in swinir_gray_dn_urls.items():
    fname = url.split('/')[-1]
    dst = SWINIR_MODEL_DIR / fname
    if not dst.exists():
        run(f'wget {shell_quote(url)} -P {shell_quote(str(SWINIR_MODEL_DIR))}')
    else:
        print(f'SwinIR noise{noise_level} weight already exists:', dst)

# 3) Load models and define preprocessing helpers

if str(NAFNET_DIR) not in sys.path:
    sys.path.insert(0, str(NAFNET_DIR))

from basicsr.models import create_model
from basicsr.utils import img2tensor as img2tensor_for_naf, tensor2img
from basicsr.utils.options import parse

# ---------- NAFNet ----------
opt_path = NAFNET_DIR / 'options' / 'test' / 'REDS' / 'NAFNet-width64.yml'
opt = parse(str(opt_path), is_train=False)
opt['dist'] = False
opt['path']['pretrain_network_g'] = str(NAFNET_WEIGHT_DIR / 'NAFNet-REDS-width64.pth')
NAFNet = create_model(opt)

# ---------- SwinIR (grayscale denoise) ----------
_SWINIR_CACHE = {}
_SWINIR_DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

def _load_swinir_network_class():
    network_py = SWINIR_DIR / 'models' / 'network_swinir.py'
    if not network_py.exists():
        raise FileNotFoundError(f'Cannot find SwinIR network file: {network_py}')

    spec = importlib.util.spec_from_file_location('swinir_network_dynamic', str(network_py))
    module = importlib.util.module_from_spec(spec)
    if spec.loader is None:
        raise RuntimeError('Failed to load SwinIR network module loader.')
    spec.loader.exec_module(module)
    return module.SwinIR

def _get_swinir_gray_dn_model(noise_level: int):
    if noise_level in _SWINIR_CACHE:
        return _SWINIR_CACHE[noise_level]

    if noise_level not in (15, 25, 50):
        raise ValueError('noise_level must be one of 15, 25, 50')

    model_path = SWINIR_MODEL_DIR / f'004_grayDN_DFWB_s128w8_SwinIR-M_noise{noise_level}.pth'
    if not model_path.exists():
        raise FileNotFoundError(f'Missing SwinIR model: {model_path}')

    SwinIRClass = _load_swinir_network_class()

    model = SwinIRClass(
        upscale=1,
        in_chans=1,
        img_size=128,
        window_size=8,
        img_range=1.0,
        depths=[6, 6, 6, 6, 6, 6],
        embed_dim=180,
        num_heads=[6, 6, 6, 6, 6, 6],
        mlp_ratio=2,
        upsampler='',
        resi_connection='1conv',
    )

    checkpoint = torch.load(str(model_path), map_location='cpu')
    if isinstance(checkpoint, dict):
        if 'params_ema' in checkpoint:
            checkpoint = checkpoint['params_ema']
        elif 'params' in checkpoint:
            checkpoint = checkpoint['params']

    model.load_state_dict(checkpoint, strict=False)
    model.eval().to(_SWINIR_DEVICE)

    _SWINIR_CACHE[noise_level] = model
    print(f'SwinIR gray denoise model loaded: noise={noise_level}, device={_SWINIR_DEVICE}')
    return model

# ---------- Image helpers ----------
def read_gray_image(path: Path) -> np.ndarray:
    img = cv2.imread(str(path), cv2.IMREAD_UNCHANGED)
    if img is None:
        raise FileNotFoundError(f'Cannot read image: {path}')
    if img.ndim == 3:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    if img.dtype != np.uint8:
        img = cv2.normalize(img, None, 0, 255, cv2.NORM_MINMAX).astype(np.uint8)
    return img

def gray_to_rgb(gray_img: np.ndarray) -> np.ndarray:
    return np.stack([gray_img, gray_img, gray_img], axis=-1)

def apply_clahe_gray(image_gray: np.ndarray, clip_limit: float = 2.0, grid_size: int = 8) -> np.ndarray:
    clahe = cv2.createCLAHE(clipLimit=float(clip_limit), tileGridSize=(int(grid_size), int(grid_size)))
    return clahe.apply(image_gray)

@torch.no_grad()
def swinir_denoise_gray(gray_img: np.ndarray, noise_level: int = 25) -> np.ndarray:
    model = _get_swinir_gray_dn_model(noise_level)

    x = gray_img.astype(np.float32) / 255.0
    x = torch.from_numpy(x).unsqueeze(0).unsqueeze(0).to(_SWINIR_DEVICE)

    window_size = 8
    h_old, w_old = x.shape[2], x.shape[3]
    h_pad = (window_size - h_old % window_size) % window_size
    w_pad = (window_size - w_old % window_size) % window_size

    if h_pad > 0:
        x = torch.cat([x, torch.flip(x, dims=[2])], dim=2)[:, :, :h_old + h_pad, :]
    if w_pad > 0:
        x = torch.cat([x, torch.flip(x, dims=[3])], dim=3)[:, :, :, :w_old + w_pad]

    y = model(x)
    y = y[:, :, :h_old, :w_old]

    y = y.squeeze().float().cpu().clamp_(0, 1).numpy()
    return (y * 255.0).round().astype(np.uint8)

def nafnet_deblur_gray(gray_img: np.ndarray) -> np.ndarray:
    rgb = gray_to_rgb(gray_img)
    inp = img2tensor_for_naf(rgb.astype(np.float32) / 255.0, bgr2rgb=False, float32=True)

    NAFNet.feed_data(data={'lq': inp.unsqueeze(dim=0)})
    if NAFNet.opt['val'].get('grids', False):
        NAFNet.grids()
    NAFNet.test()
    if NAFNet.opt['val'].get('grids', False):
        NAFNet.grids_inverse()

    visuals = NAFNet.get_current_visuals()
    sr_img = tensor2img([visuals['result']])

    if sr_img.ndim == 3:
        return np.mean(sr_img, axis=2).astype(np.uint8)
    return sr_img.astype(np.uint8)

def preprocess_single_image(
    image_path: Path,
    noise_level: int = 25,
    clahe_clip_limit: float = 2.0,
    clahe_grid_size: int = 8,
):
    original = read_gray_image(image_path)
    denoised = swinir_denoise_gray(original, noise_level=noise_level)
    denoise_deblur = nafnet_deblur_gray(denoised)
    final = apply_clahe_gray(
        denoise_deblur,
        clip_limit=clahe_clip_limit,
        grid_size=clahe_grid_size,
    )

    return {
        'original': original,
        'denoised': denoised,
        'denoise_deblur': denoise_deblur,
        'final': final,
    }

print('Models and helpers are ready.')

# 4) Configure your input/output directories and parameters

# Set this to your input image directory
INPUT_DIR = Path('/content/drive/MyDrive/Thyroid Project/cf_dataset/images')

# Processed outputs will be saved here
OUTPUT_DIR = Path('/content/preprocessed_output')

# Zip file path for easy download
ZIP_PATH = Path('/content/preprocessed_output.zip')

# Processing parameters
NOISE_LEVEL = 25        # SwinIR noise level: 15, 25, or 50
CLAHE_CLIP_LIMIT = 2.0
CLAHE_GRID_SIZE = 8

# Output behavior
CLEAN_OUTPUT_DIR = True
OUTPUT_SUFFIX = '_preprocessed'

VALID_EXTS = {'.png', '.jpg', '.jpeg', '.bmp', '.tif', '.tiff'}

print('INPUT_DIR:', INPUT_DIR)
print('OUTPUT_DIR:', OUTPUT_DIR)
print('ZIP_PATH:', ZIP_PATH)

# 5) Run batch preprocessing: Denoise -> Deblur -> CLAHE

if not INPUT_DIR.exists():
    raise FileNotFoundError(f'Input directory does not exist: {INPUT_DIR}')

input_paths = sorted([p for p in INPUT_DIR.iterdir() if p.is_file() and p.suffix.lower() in VALID_EXTS])
if not input_paths:
    raise RuntimeError(f'No images found in {INPUT_DIR} with extensions {sorted(VALID_EXTS)}')

if CLEAN_OUTPUT_DIR and OUTPUT_DIR.exists():
    shutil.rmtree(OUTPUT_DIR)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

processed_pairs = []
start_time = time.time()

print(f'Found {len(input_paths)} images. Starting batch processing...')

for idx, in_path in enumerate(input_paths, start=1):
    steps = preprocess_single_image(
        in_path,
        noise_level=NOISE_LEVEL,
        clahe_clip_limit=CLAHE_CLIP_LIMIT,
        clahe_grid_size=CLAHE_GRID_SIZE,
    )

    out_name = f"{in_path.stem}{OUTPUT_SUFFIX}.png"
    out_path = OUTPUT_DIR / out_name
    cv2.imwrite(str(out_path), steps['final'])

    processed_pairs.append((in_path, out_path))

    if idx % 10 == 0 or idx == len(input_paths):
        print(f'Processed {idx}/{len(input_paths)}')

elapsed = time.time() - start_time
print()
print(f'Done. Processed {len(processed_pairs)} images in {elapsed:.1f}s')
print('Output directory:', OUTPUT_DIR)

# 6) Zip output directory and prepare download

if ZIP_PATH.exists():
    ZIP_PATH.unlink()

with zipfile.ZipFile(ZIP_PATH, 'w', compression=zipfile.ZIP_DEFLATED) as zf:
    for _, out_path in processed_pairs:
        zf.write(str(out_path), arcname=out_path.name)

print('Zip created:', ZIP_PATH)

# Colab download (fallback to a local path print if not in Colab)
try:
    from google.colab import files
    files.download(str(ZIP_PATH))
except Exception:
    print('Not running in Colab download context. You can manually download:')
    print(ZIP_PATH)

# 7) Visualization: pick 5 random images and show 4-step pipeline columns

if not input_paths:
    raise RuntimeError('No input images were loaded. Run the batch cell first.')

sample_n = min(5, len(input_paths))
random.seed(42)
sample_paths = random.sample(input_paths, k=sample_n)

col_titles = [
    'Original',
    'After Denoise (SwinIR)',
    'After Denoise + Deblur (NAFNet)',
    'After Denoise + Deblur + CLAHE (Final)',
]

fig, axes = plt.subplots(sample_n, 4, figsize=(20, 5 * sample_n))
if sample_n == 1:
    axes = np.expand_dims(axes, axis=0)

for i, img_path in enumerate(sample_paths):
    steps = preprocess_single_image(
        img_path,
        noise_level=NOISE_LEVEL,
        clahe_clip_limit=CLAHE_CLIP_LIMIT,
        clahe_grid_size=CLAHE_GRID_SIZE,
    )

    row_imgs = [
        steps['original'],
        steps['denoised'],
        steps['denoise_deblur'],
        steps['final'],
    ]

    for j in range(4):
        ax = axes[i, j]
        ax.imshow(row_imgs[j], cmap='gray', vmin=0, vmax=255)
        ax.axis('off')
        if i == 0:
            ax.set_title(col_titles[j], fontsize=13)

    axes[i, 0].set_ylabel(img_path.name, fontsize=11)

plt.tight_layout()
plt.show()

"""## Notes

- Final saved outputs are from the main pipeline: **Denoise -> Deblur -> CLAHE**.
- If your images are very large and GPU memory is limited, use fewer images at a time or resize inputs before processing.

"""